version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          context: dev
          command: |
            echo "${ENV_NAME}"
            echo "${#ENV_DESCRIPTION}"
